// <auto-generated />
using System;
using JWT_Project_Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JWT_Project_Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251114083222_CreateDataBaseQLSanPhamSach")]
    partial class CreateDataBaseQLSanPhamSach
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JWT_Project_Core.Model.HoaDon", b =>
                {
                    b.Property<Guid>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaHoaDon");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("JWT_Project_Core.Model.HoaDon_Sach", b =>
                {
                    b.Property<Guid>("MaHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSach")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDon", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("HoaDon_Sach");
                });

            modelBuilder.Entity("JWT_Project_Core.Model.Sach", b =>
                {
                    b.Property<string>("MaSach")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<double>("GiaNhap")
                        .HasColumnType("float");

                    b.Property<string>("NoiDungSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTacGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSach");

                    b.ToTable("Saches");
                });

            modelBuilder.Entity("JWT_Project_Core.Model.HoaDon_Sach", b =>
                {
                    b.HasOne("JWT_Project_Core.Model.HoaDon", "HoaDon")
                        .WithMany("HoaDon_Saches")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JWT_Project_Core.Model.Sach", "Sach")
                        .WithMany("HoaDon_Saches")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("JWT_Project_Core.Model.HoaDon", b =>
                {
                    b.Navigation("HoaDon_Saches");
                });

            modelBuilder.Entity("JWT_Project_Core.Model.Sach", b =>
                {
                    b.Navigation("HoaDon_Saches");
                });
#pragma warning restore 612, 618
        }
    }
}
